//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4927
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=2.0.50727.3038.
// 

namespace declarant.xml11
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Файл
    {

        private ФайлОборот[] документField;

        private string датаДокField;

        private ФайлВерсФорм версФормField;

        private string наимПрогField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Оборот", IsNullable = false)]
        public ФайлОборот[] Документ
        {
            get { return this.документField; }
            set { this.документField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаДок
        {
            get { return this.датаДокField; }
            set { this.датаДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлВерсФорм ВерсФорм
        {
            get { return this.версФормField; }
            set { this.версФормField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимПрог
        {
            get { return this.наимПрогField; }
            set { this.наимПрогField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлОборот
    {

        private ФайлОборотСведПроизвИмпорт[] сведПроизвИмпортField;

        private int пnField;

        private ФайлОборотП000000000003 п000000000003Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведПроизвИмпорт")]
        public ФайлОборотСведПроизвИмпорт[] СведПроизвИмпорт
        {
            get { return this.сведПроизвИмпортField; }
            set { this.сведПроизвИмпортField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ПN
        {
            get { return this.пnField; }
            set { this.пnField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлОборотП000000000003 П000000000003
        {
            get { return this.п000000000003Field; }
            set { this.п000000000003Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлОборотСведПроизвИмпорт
    {

        private ФайлОборотСведПроизвИмпортПродукция[] продукцияField;

        private ФайлОборотСведПроизвИмпортДвижение[] движениеField;

        private string nameOrgField;

        private string iNNField;

        private string kPPField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Продукция")]
        public ФайлОборотСведПроизвИмпортПродукция[] Продукция
        {
            get { return this.продукцияField; }
            set { this.продукцияField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Движение")]
        public ФайлОборотСведПроизвИмпортДвижение[] Движение
        {
            get { return this.движениеField; }
            set { this.движениеField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOrg
        {
            get { return this.nameOrgField; }
            set { this.nameOrgField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN
        {
            get { return this.iNNField; }
            set { this.iNNField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KPP
        {
            get { return this.kPPField; }
            set { this.kPPField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлОборотСведПроизвИмпортПродукция
    {
        private string пSUPPLIER_INNField;

        private string п200000000013Field;

        private string п200000000014Field;

        private string п200000000015Field;

        private decimal п200000000016Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SUPPLIER_INN {
            get { return this.пSUPPLIER_INNField; }
            set { this.пSUPPLIER_INNField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П200000000013
        {
            get { return this.п200000000013Field; }
            set { this.п200000000013Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П200000000014
        {
            get { return this.п200000000014Field; }
            set { this.п200000000014Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П200000000015
        {
            get { return this.п200000000015Field; }
            set { this.п200000000015Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П200000000016
        {
            get { return this.п200000000016Field; }
            set { this.п200000000016Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлОборотСведПроизвИмпортДвижение
    {

        private int пnField;

        private decimal п100000000006Field;

        private decimal п100000000007Field;

        private decimal п100000000008Field;

        private decimal п100000000009Field;

        private decimal п100000000010Field;

        private decimal п100000000011Field;

        private decimal п100000000012Field;

        private decimal п100000000013Field;

        private decimal п100000000014Field;

        private decimal п100000000015Field;

        private decimal п100000000016Field;

        private decimal п100000000017Field;

        private decimal п100000000018Field;

        private decimal п100000000019Field;

        private decimal п100000000020Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ПN
        {
            get { return this.пnField; }
            set { this.пnField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000006
        {
            get { return this.п100000000006Field; }
            set { this.п100000000006Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000007
        {
            get { return this.п100000000007Field; }
            set { this.п100000000007Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000008
        {
            get { return this.п100000000008Field; }
            set { this.п100000000008Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000009
        {
            get { return this.п100000000009Field; }
            set { this.п100000000009Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000010
        {
            get { return this.п100000000010Field; }
            set { this.п100000000010Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000011
        {
            get { return this.п100000000011Field; }
            set { this.п100000000011Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000012
        {
            get { return this.п100000000012Field; }
            set { this.п100000000012Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000013
        {
            get { return this.п100000000013Field; }
            set { this.п100000000013Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000014
        {
            get { return this.п100000000014Field; }
            set { this.п100000000014Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000015
        {
            get { return this.п100000000015Field; }
            set { this.п100000000015Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000016
        {
            get { return this.п100000000016Field; }
            set { this.п100000000016Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000017
        {
            get { return this.п100000000017Field; }
            set { this.п100000000017Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000018
        {
            get { return this.п100000000018Field; }
            set { this.п100000000018Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000019
        {
            get { return this.п100000000019Field; }
            set { this.п100000000019Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal П100000000020
        {
            get { return this.п100000000020Field; }
            set { this.п100000000020Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлОборотП000000000003
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("010")] Item010,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("020")] Item020,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("025")] Item025,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("030")] Item030,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("040")] Item040,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("050")] Item050,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("060")] Item060,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("070")] Item070,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("080")] Item080,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("090")] Item090,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("200")] Item200,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("211")] Item211,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("212")] Item212,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("221")] Item221,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("229")] Item229,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("230")] Item230,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("231")] Item231,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("232")] Item232,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("239")] Item239,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("241")] Item241,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("242")] Item242,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("250")] Item250,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("251")] Item251,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")] Item260,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("270")] Item270,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("280")] Item280,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("400")] Item400,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("402")] Item402,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("403")] Item403,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("410")] Item410,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("420")] Item420,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("421")] Item421,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("440")] Item440,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("450")] Item450,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("460")] Item460,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("320")] Item320,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("330")] Item330,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("331")] Item331,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("340")] Item340,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("300")] Item300,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("310")] Item310,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("350")] Item350,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("401")] Item401,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("461")] Item461,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("462")] Item462,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("481")] Item481,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("482")] Item482,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("483")] Item483,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("484")] Item484,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("500")] Item500,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("510")] Item510,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("520")] Item520,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлВерсФорм
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4.20")] Item420,
    }
}