//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4927
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=2.0.50727.3038.
// 

namespace declarant.xml
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Справочники
    {
        private СправочникиКонтрагенты[] контрагентыField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Контрагенты", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)
        ]
        public СправочникиКонтрагенты[] Контрагенты
        {
            get { return this.контрагентыField; }
            set { this.контрагентыField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СправочникиКонтрагенты
    {
        private object itemField;

        private int идКонтрField;

        private string п000000000007Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Иностр", typeof (СправочникиКонтрагентыИностр),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Резидент", typeof (СправочникиКонтрагентыРезидент),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ИдКонтр
        {
            get { return this.идКонтрField; }
            set { this.идКонтрField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000007
        {
            get { return this.п000000000007Field; }
            set { this.п000000000007Field = value; }
        }

        /// <summary>
        /// Контрагент является резидентом
        /// </summary>
        /// <returns></returns>
        public bool isResident() {
            if (Item is СправочникиКонтрагентыРезидент) {
                object residentItem = ((СправочникиКонтрагентыРезидент)Item).Item;
                if (residentItem is СправочникиКонтрагентыРезидентЮЛ) {
                    return true;
                } else {
                    return true;
                }
            } else {
                return false;
            }
        }

        /// <summary>
        /// Получить строку для поиска в БД
        /// </summary>
        /// <returns></returns>
        public string getContragentSearchIndex() {
            if (isResident()) {
                return getContragentInn();
            } else {
                return П000000000007;
            }
        }

        public string getContragentInn() {
            if (isResident()) {
                object residentItem = ((СправочникиКонтрагентыРезидент)Item).Item;
                if (residentItem is СправочникиКонтрагентыРезидентЮЛ) {
                    return ((СправочникиКонтрагентыРезидентЮЛ)residentItem).П000000000009;
                } else {
                    return ((СправочникиКонтрагентыРезидентФЛ)residentItem).П000000000009;
                }
            } else {
                return String.Empty;
            }
        }

        public string getContragentKpp() {
            if (isResident()) {
                object residentItem = ((СправочникиКонтрагентыРезидент)Item).Item;
                if (residentItem is СправочникиКонтрагентыРезидентЮЛ) {
                    return ((СправочникиКонтрагентыРезидентЮЛ)residentItem).П000000000010;
                } else {
                    return String.Empty;
                }
            } else {
                return String.Empty;
            }
        }

        private АдрТип getAddress() {
            if (isResident()) {
                return ((СправочникиКонтрагентыРезидент)Item).П000000000008;
            } else {
                return null;
            }
        }

        public string getContragentCountryCode() {
            if (isResident()) {
                return getAddress().КодСтраны;
            } else {
                return ((СправочникиКонтрагентыИностр)Item).П000000000081;
            }
        }

        public string getContragentIndex() {
            if (isResident()) {
                return getAddress().Индекс;
            } else {
                return String.Empty;
            }
        }

        public string getContragentRegion() {
            if (isResident()) {
                return getAddress().КодРегион;
            } else {
                return String.Empty;
            }
        }

        public string getContragentArea() {
            if (isResident()) {
                return getAddress().Район;
            } else {
                return String.Empty;
            }
        }

        public string getContragentCity() {
            if (isResident()) {
                return getAddress().Город;
            } else {
                return String.Empty;
            }
        }

        public string getContragentPlace() {
            if (isResident()) {
                return getAddress().НаселПункт;
            } else {
                return String.Empty;
            }
        }

        public string getContragentStreet() {
            if (isResident()) {
                return getAddress().Улица;
            } else {
                return String.Empty;
            }
        }

        public string getContragentBuilding() {
            if (isResident()) {
                return getAddress().Дом;
            } else {
                return String.Empty;
            }
        }

        public string getContragentKorp() {
            if (isResident()) {
                return getAddress().Корпус;
            } else {
                return String.Empty;
            }
        }

        public string getContragentFlat() {
            if (isResident()) {
                return getAddress().Кварт;
            } else {
                return String.Empty;
            }
        }

        public string getContragentLiter() {
            if (isResident()) {
                return getAddress().Литера;
            } else {
                return String.Empty;
            }
        }

        public string getContragentForeignAddres() {
            if (isResident()) {
                return String.Empty;
            } else {
                return ((СправочникиКонтрагентыИностр)Item).П000000000082;
            }
        }

        public int getContragentOrgType() {
            return (isResident() ? 1 : 3);

        }

        public bool getContragentProducer() {
              if (isResident()) {
                return bool.Parse(((СправочникиКонтрагентыРезидент)Item).Производитель.value);
            } else {
                return false;
            }
        }

        public bool getContragentCarrier() {
              if (isResident()) {
                return bool.Parse(((СправочникиКонтрагентыРезидент)Item).Перевозчик.value);
            } else {
                return false;
            }
        }

        public СправочникиКонтрагентыРезидентЛицензии[] getLicenses()
        {
            if (isResident())
            {
                return ((СправочникиКонтрагентыРезидент) Item).Лицензии;
            } else {
                return null;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СправочникиКонтрагентыИностр
    {

        private string п000000000081Field;

        private string п000000000082Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000081
        {
            get { return this.п000000000081Field; }
            set { this.п000000000081Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000082
        {
            get { return this.п000000000082Field; }
            set { this.п000000000082Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрТип
    {

        private string кодСтраныField;

        private string индексField;

        private string кодРегионField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string улицаField;

        private string домField;

        private string корпусField;

        private string литераField;

        private string квартField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодСтраны
        {
            get { return this.кодСтраныField; }
            set { this.кодСтраныField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Индекс
        {
            get { return this.индексField; }
            set { this.индексField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодРегион
        {
            get { return this.кодРегионField; }
            set { this.кодРегионField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Район
        {
            get { return this.районField; }
            set { this.районField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Город
        {
            get { return this.городField; }
            set { this.городField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаселПункт
        {
            get { return this.населПунктField; }
            set { this.населПунктField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Улица
        {
            get { return this.улицаField; }
            set { this.улицаField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Дом
        {
            get { return this.домField; }
            set { this.домField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Корпус
        {
            get { return this.корпусField; }
            set { this.корпусField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Литера
        {
            get { return this.литераField; }
            set { this.литераField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Кварт
        {
            get { return this.квартField; }
            set { this.квартField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СправочникиКонтрагентыРезидент
    {

        private СправочникиКонтрагентыРезидентЛицензии[] лицензииField;

        private АдрТип п000000000008Field;

        private object itemField;

        private СправочникиКонтрагентыРезидентПроизводитель производительField;

        private СправочникиКонтрагентыРезидентПеревозчик перевозчикField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Лицензии", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СправочникиКонтрагентыРезидентЛицензии[] Лицензии
        {
            get { return this.лицензииField; }
            set { this.лицензииField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public АдрТип П000000000008
        {
            get { return this.п000000000008Field; }
            set { this.п000000000008Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФЛ", typeof (СправочникиКонтрагентыРезидентФЛ),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ЮЛ", typeof (СправочникиКонтрагентыРезидентЮЛ),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СправочникиКонтрагентыРезидентПроизводитель Производитель
        {
            get { return this.производительField; }
            set { this.производительField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СправочникиКонтрагентыРезидентПеревозчик Перевозчик
        {
            get { return this.перевозчикField; }
            set { this.перевозчикField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СправочникиКонтрагентыРезидентЛицензии
    {

        private СправочникиКонтрагентыРезидентЛицензииЛицензия лицензияField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СправочникиКонтрагентыРезидентЛицензииЛицензия Лицензия
        {
            get { return this.лицензияField; }
            set { this.лицензияField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СправочникиКонтрагентыРезидентЛицензииЛицензия
    {

        private int идЛицензииField;

        private string п000000000011Field;

        private string п000000000012Field;

        private string п000000000013Field;

        private string п000000000014Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ИдЛицензии
        {
            get { return this.идЛицензииField; }
            set { this.идЛицензииField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000011
        {
            get { return this.п000000000011Field; }
            set { this.п000000000011Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000012
        {
            get { return this.п000000000012Field; }
            set { this.п000000000012Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000013
        {
            get { return this.п000000000013Field; }
            set { this.п000000000013Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000014
        {
            get { return this.п000000000014Field; }
            set { this.п000000000014Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СправочникиКонтрагентыРезидентФЛ
    {

        private string п000000000009Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000009
        {
            get { return this.п000000000009Field; }
            set { this.п000000000009Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СправочникиКонтрагентыРезидентЮЛ
    {

        private string п000000000009Field;

        private string п000000000010Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000009
        {
            get { return this.п000000000009Field; }
            set { this.п000000000009Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П000000000010
        {
            get { return this.п000000000010Field; }
            set { this.п000000000010Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СправочникиКонтрагентыРезидентПроизводитель
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СправочникиКонтрагентыРезидентПеревозчик
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

}